### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by andymaheshw** [andymaheshw/AdobeAnalytics#13]
Hi Randy, I created the testing branch, I'll get them done soon. 

I think we're all set after tests right? We just need to push to pypi?

**Comment by randyzwitch** [comment]
Well, there's still a handful of outstanding issues. Most pressing is that the package doesn't appear to be valid:

```python
Randys-MacBook-Pro:~ randyzwitch$ pip install git+https://github.com/andymaheshw/AdobeAnalytics
Collecting git+https://github.com/andymaheshw/AdobeAnalytics
  Cloning https://github.com/andymaheshw/AdobeAnalytics to /var/folders/52/wl2rr05s3xgd8jy28j0_7bhm0000gn/T/pip-2wbTFB-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/52/wl2rr05s3xgd8jy28j0_7bhm0000gn/T/pip-2wbTFB-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/52/wl2rr05s3xgd8jy28j0_7bhm0000gn/T/pip-2wbTFB-build/
```

I would think that the outstanding tasks are:

- [ ] Make a valid package
- [ ] Get tests setup correctly through Travis (using the authentication tokens). Luckily, there is easy to understand documentation from someone you might be familiar with: http://randyzwitch.com/authentication-travis-ci/
- [] Write documentation of current methods
- [] (optional) Implement Queue methods
- [] (optional) remove Pandas as a dependency, until pandas functionality is actually used in the package

I know you were looking for help with the Queue methods, and I'm still willing to help. It's up to you whether you want to get a 0.1 version out on PyPI so it's discoverable, then work on the Queue methods or do the queue methods first (since they are arguably the most useful methods).

**Comment by randyzwitch** [comment]
And probably should resolve the naming once and for all. PEP8 says that package module names should be all lowercase.

Started a new branch make-valid-package to work on the pip issues. Hopefully I can get it figured out today, I've actually never tried to make a valid Python package!

**Comment by randyzwitch** [comment]
So technically, this works now:

```python
Randys-MacBook-Pro:~ randyzwitch$ pip install git+https://github.com/andymaheshw/AdobeAnalytics@make-valid-package
Collecting git+https://github.com/andymaheshw/AdobeAnalytics@make-valid-package
  Cloning https://github.com/andymaheshw/AdobeAnalytics (to make-valid-package) to /var/folders/52/wl2rr05s3xgd8jy28j0_7bhm0000gn/T/pip-VzgyLR-build
Requirement already satisfied (use --upgrade to upgrade): pandas in ./anaconda3/lib/python2.7/site-packages (from AdobeAnalytics==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./anaconda3/lib/python2.7/site-packages (from AdobeAnalytics==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pytz in ./anaconda3/lib/python2.7/site-packages (from AdobeAnalytics==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): requests in ./anaconda3/lib/python2.7/site-packages (from AdobeAnalytics==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): six in ./anaconda3/lib/python2.7/site-packages (from AdobeAnalytics==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in ./anaconda3/lib/python2.7/site-packages (from pandas->AdobeAnalytics==0.1.0)
Installing collected packages: AdobeAnalytics
  Running setup.py install for AdobeAnalytics ... done
Successfully installed AdobeAnalytics-0.1.0
```

**Comment by randyzwitch** [comment]
Added my Travis keys to the file. As far as I can tell, both of us should be able to do the Travis tests (since we're both working out of this same repo).

Your tests branch is probably out of date now, so you might want to branch off `add-auth-keys`; I'm going to keep working on this, hopefully I can get one test working. From there it will be easy to get a bunch of tests going.

**Comment by andymaheshw** [comment]
So I've been trying to read about how to store environment variables for running tests in Travis CI, and I've updated my tests branch as well.

**Comment by andymaheshw** [comment]
I found the commands to push to pypi and played with them a bit, we're almost there!

**Comment by andymaheshw** [comment]
Also you didn't put your name on the package, so I added it to setup.py :)

**Comment by randyzwitch** [comment]
Per the Travis build, I removed unused packages in #15 and tests against the Adobe API actually work (for Python 2.7)
